name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build plugin
      run: npm run build
      
    - name: Create release directory
      run: |
        mkdir release
        cp main.js manifest.json styles.css release/
        
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Create zip archive
      run: |
        cd release
        zip -r ../obsidian-discord-bridge-${{ steps.get_version.outputs.VERSION }}.zip .
        cd ..
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          obsidian-discord-bridge-${{ steps.get_version.outputs.VERSION }}.zip
          main.js
          manifest.json
          styles.css
        body: |
          ## 🚀 Release ${{ steps.get_version.outputs.VERSION }}
          
          ### 📦 Installation
          1. Download `obsidian-discord-bridge-${{ steps.get_version.outputs.VERSION }}.zip`
          2. Extract to your Obsidian plugins folder: `VaultFolder/.obsidian/plugins/obsidian-discord-bridge/`
          3. Restart Obsidian and enable the plugin in settings
          
          ### 🔧 Manual Installation
          Alternatively, download the individual files:
          - `main.js`
          - `manifest.json` 
          - `styles.css`
          
          And place them in: `VaultFolder/.obsidian/plugins/obsidian-discord-bridge/`
          
          ### 📚 Documentation
          See the [README](https://github.com/yuu1111/obsidian-discord-bridge/blob/master/README.md) for setup instructions.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}