name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build plugin
      run: npm run build
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
    - name: Verify build artifacts exist
      run: |
        echo "Checking required files..."
        ls -la main.js manifest.json styles.css
        echo "All required files found!"
        
    - name: Create release directory and copy files
      run: |
        mkdir -p release
        cp main.js manifest.json styles.css release/
        echo "Files copied to release directory:"
        ls -la release/
        
    - name: Create plugin zip archive
      run: |
        cd release
        zip -r ../obsidian-discord-bridge-${{ steps.get_version.outputs.VERSION }}.zip .
        cd ..
        echo "Created zip file: obsidian-discord-bridge-${{ steps.get_version.outputs.VERSION }}.zip"
        ls -la obsidian-discord-bridge-${{ steps.get_version.outputs.VERSION }}.zip
        
    - name: Generate checksums
      run: |
        echo "Generating checksums..."
        sha256sum obsidian-discord-bridge-${{ steps.get_version.outputs.VERSION }}.zip > checksums.txt
        sha256sum main.js >> checksums.txt
        sha256sum manifest.json >> checksums.txt
        sha256sum styles.css >> checksums.txt
        echo "Checksums:"
        cat checksums.txt
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          obsidian-discord-bridge-${{ steps.get_version.outputs.VERSION }}.zip
          main.js
          manifest.json
          styles.css
          checksums.txt
        body: |
          ## 🚀 Release ${{ steps.get_version.outputs.VERSION }}
          
          ### 📦 Easy Installation
          **Recommended:** Download `obsidian-discord-bridge-${{ steps.get_version.outputs.VERSION }}.zip`
          
          1. Download the zip file below
          2. Extract to: `YourVault/.obsidian/plugins/obsidian-discord-bridge/`
          3. Restart Obsidian
          4. Enable "Discord Bridge" in Settings → Community plugins
          
          ### 🔧 Manual Installation
          Download individual files and place in `YourVault/.obsidian/plugins/obsidian-discord-bridge/`:
          - `main.js` - Main plugin code
          - `manifest.json` - Plugin metadata
          - `styles.css` - Plugin styles
          
          ### 🔒 Security
          - `checksums.txt` - SHA256 checksums for file verification
          - All files are digitally signed by GitHub Actions
          
          ### 📚 Setup Guide
          See the [README](https://github.com/yuu1111/obsidian-discord-bridge/blob/master/README.md) for Discord bot configuration.
          
          ### 🆕 What's New
          Check the commit history for detailed changes in this release.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}